In [1]:
import pandas as pd
import requests
import json

In [2]:
fhirexample = [{
    "resourceType": "Condition",
    "id": "zib-burnwound-01",
    "meta": {
        "profile":  [
            "http://nictiz.nl/fhir/StructureDefinition/zib-BurnWound"
        ]
    },
    "extension":  [
        {
            "url": "http://nictiz.nl/fhir/StructureDefinition/condition-dateOfLastDressingChange",
            "valueDateTime": "2019-03-07"
        },
        {
            "url": "http://nictiz.nl/fhir/StructureDefinition/zib-BurnWound-Extent",
            "valueQuantity": {
                "value": 1,
                "unit": "%",
                "system": "http://unitsofmeasure.org",
                "code": "%"
            }
        }
    ],
    "identifier":  [
        {
            "system": "urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6",
            "value": "1234"
        },
        {
            "system": "urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4",
            "value": "4578"
        }
    ],
    "clinicalStatus": "active",
    "verificationStatus": "unknown",
    "code": {
        "extension":  [
            {
                "url": "http://nictiz.nl/fhir/StructureDefinition/zib-BurnWound-BurnWoundType",
                "valueCodeableConcept": {
                    "coding":  [
                        {
                            "system": "http://snomed.info/sct",
                            "code": "105594005",
                            "display": "Thermische brandwond"
                        }
                    ]
                }
            }
        ],
        "coding":  [
            {
                "system": "http://snomed.info/sct",
                "code": "125666000",
                "display": "Burn (disorder)"
            }
        ]
    },
    "bodySite":  [
        {
            "extension":  [
                {
                    "url": "http://nictiz.nl/fhir/StructureDefinition/BodySite-Qualifier",
                    "valueCodeableConcept": {
                        "coding":  [
                            {
                                "system": "http://snomed.info/sct",
                                "code": "24028007",
                                "display": "Right"
                            }
                        ]
                    }
                }
            ],
            "coding":  [
                {
                    "system": "http://snomed.info/sct",
                    "code": "362746006",
                    "display": "structuur van oppervlak van dorsum manus"
                }
            ]
        }
    ],
    "subject": {
        "reference": "Patient/nl-core-patient-01",
        "display": "Johan XXX_Helleman"
    },
    "onsetDateTime": "2018-08-16",
    "stage": {
        "summary": {
            "coding":  [
                {
                    "system": "http://snomed.info/sct",
                    "code": "262588000",
                    "display": "3e graad"
                }
            ]
        }
    },
    "note":  [
        {
            "text": "Werkongeval in de hoogovens IJmuiden."
        }
    ]
},
{
    "resourceType": "Condition",
    "id": "zib-burnwound-02",
    "meta": {
        "profile":  [
            "http://nictiz.nl/fhir/StructureDefinition/zib-BurnWound"
        ]
    },
    "extension":  [
        {
            "url": "http://nictiz.nl/fhir/StructureDefinition/condition-dateOfLastDressingChange",
            "valueDateTime": "2020-03-07"
        },
        {
            "url": "http://nictiz.nl/fhir/StructureDefinition/zib-BurnWound-Extent",
            "valueQuantity": {
                "value": 1,
                "unit": "%",
                "system": "http://unitsofmeasure.org",
                "code": "%"
            }
        }
    ],
    "identifier":  [
        {
            "system": "urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6",
            "value": "5460"
        },
        {
            "system": "urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4",
            "value": "3433"
        }
    ],
    "clinicalStatus": "active",
    "verificationStatus": "unknown",
    "code": {
        "extension":  [
            {
                "url": "http://nictiz.nl/fhir/StructureDefinition/zib-BurnWound-BurnWoundType",
                "valueCodeableConcept": {
                    "coding":  [
                        {
                            "system": "http://snomed.info/sct",
                            "code": "105594005",
                            "display": "Thermische brandwond"
                        }
                    ]
                }
            }
        ],
        "coding":  [
            {
                "system": "http://snomed.info/sct",
                "code": "125666000",
                "display": "Burn (disorder)"
            }
        ]
    },
    "bodySite":  [
        {
            "extension":  [
                {
                    "url": "http://nictiz.nl/fhir/StructureDefinition/BodySite-Qualifier",
                    "valueCodeableConcept": {
                        "coding":  [
                            {
                                "system": "http://snomed.info/sct",
                                "code": "24028007",
                                "display": "Right"
                            }
                        ]
                    }
                }
            ],
            "coding":  [
                {
                    "system": "http://snomed.info/sct",
                    "code": "362746006",
                    "display": "structuur van oppervlak van dorsum manus"
                }
            ]
        }
    ],
    "subject": {
        "reference": "Patient/nl-core-patient-02",
        "display": "Jan Janssen"
    },
    "onsetDateTime": "2019-08-16",
    "stage": {
        "summary": {
            "coding":  [
                {
                    "system": "http://snomed.info/sct",
                    "code": "262588000",
                    "display": "3e graad"
                }
            ]
        }
    },
    "note":  [
        {
            "text": "Vuurwerk"
        }
    ]
}
]

In [3]:
pd.json_normalize(fhirexample)

,resourceType,id,extension,identifier,clinicalStatus,verificationStatus,bodySite,onsetDateTime,note,meta.profile,code.extension,code.coding,subject.reference,subject.display,stage.summary.coding
0,Condition,zib-burnwound-01,[{'url': 'http://nictiz.nl/fhir/StructureDefin...,[{'system': 'urn:oid:2.16.840.1.113883.2.4.3.1...,active,unknown,[{'extension': [{'url': 'http://nictiz.nl/fhir...,2018-08-16,[{'text': 'Werkongeval in de hoogovens IJmuide...,[http://nictiz.nl/fhir/StructureDefinition/zib...,[{'url': 'http://nictiz.nl/fhir/StructureDefin...,"[{'system': 'http://snomed.info/sct', 'code': ...",Patient/nl-core-patient-01,Johan XXX_Helleman,"[{'system': 'http://snomed.info/sct', 'code': ..."
1,Condition,zib-burnwound-02,[{'url': 'http://nictiz.nl/fhir/StructureDefin...,[{'system': 'urn:oid:2.16.840.1.113883.2.4.3.1...,active,unknown,[{'extension': [{'url': 'http://nictiz.nl/fhir...,2019-08-16,[{'text': 'Vuurwerk'}],[http://nictiz.nl/fhir/StructureDefinition/zib...,[{'url': 'http://nictiz.nl/fhir/StructureDefin...,"[{'system': 'http://snomed.info/sct', 'code': ...",Patient/nl-core-patient-02,Jan Janssen,"[{'system': 'http://snomed.info/sct', 'code': ..."

In [4]:
pd.json_normalize(fhirexample, record_path =['identifier'])

                                       system value
0  urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6  1234
1  urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4  4578
2  urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6  5460
3  urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4  3433

In [5]:
# Include meta data
pd.json_normalize(
    fhirexample, 
    record_path =['identifier'],
    meta=['resourceType', 'id']
)

,system,value,resourceType,id
0,urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6,1234,Condition,zib-burnwound-01
1,urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4,4578,Condition,zib-burnwound-01
2,urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6,5460,Condition,zib-burnwound-02
3,urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4,3433,Condition,zib-burnwound-02

In [6]:
# Include meta data
pd.json_normalize(
    fhirexample, 
    record_path =['identifier'],
    meta=['resourceType', 'id']
)

,system,value,resourceType,id
0,urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6,1234,Condition,zib-burnwound-01
1,urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4,4578,Condition,zib-burnwound-01
2,urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6,5460,Condition,zib-burnwound-02
3,urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4,3433,Condition,zib-burnwound-02

In [8]:
fhirexample

[{'resourceType': 'Condition',
  'id': 'zib-burnwound-01',
  'meta': {'profile': ['http://nictiz.nl/fhir/StructureDefinition/zib-BurnWound']},
  'extension': [{'url': 'http://nictiz.nl/fhir/StructureDefinition/condition-dateOfLastDressingChange',
    'valueDateTime': '2019-03-07'},
   {'url': 'http://nictiz.nl/fhir/StructureDefinition/zib-BurnWound-Extent',
    'valueQuantity': {'value': 1,
     'unit': '%',
     'system': 'http://unitsofmeasure.org',
     'code': '%'}}],
  'identifier': [{'system': 'urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6',
    'value': '1234'},
   {'system': 'urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4', 'value': '4578'}],
  'clinicalStatus': 'active',
  'verificationStatus': 'unknown',
  'code': {'extension': [{'url': 'http://nictiz.nl/fhir/StructureDefinition/zib-BurnWound-BurnWoundType',
     'valueCodeableConcept': {'coding': [{'system': 'http://snomed.info/sct',
        'code': '105594005',
        'display': 'Thermische brandwond'}]}}],
   'coding': [{'system': 'http://snomed.info/sct',
     'code': '125666000',
     'display': 'Burn (disorder)'}]},
  'bodySite': [{'extension': [{'url': 'http://nictiz.nl/fhir/StructureDefinition/BodySite-Qualifier',
      'valueCodeableConcept': {'coding': [{'system': 'http://snomed.info/sct',
         'code': '24028007',
         'display': 'Right'}]}}],
    'coding': [{'system': 'http://snomed.info/sct',
      'code': '362746006',
      'display': 'structuur van oppervlak van dorsum manus'}]}],
  'subject': {'reference': 'Patient/nl-core-patient-01',
   'display': 'Johan XXX_Helleman'},
  'onsetDateTime': '2018-08-16',
  'stage': {'summary': {'coding': [{'system': 'http://snomed.info/sct',
      'code': '262588000',
      'display': '3e graad'}]}},
  'note': [{'text': 'Werkongeval in de hoogovens IJmuiden.'}]},
 {'resourceType': 'Condition',
  'id': 'zib-burnwound-02',
  'meta': {'profile': ['http://nictiz.nl/fhir/StructureDefinition/zib-BurnWound']},
  'extension': [{'url': 'http://nictiz.nl/fhir/StructureDefinition/condition-dateOfLastDressingChange',
    'valueDateTime': '2020-03-07'},
   {'url': 'http://nictiz.nl/fhir/StructureDefinition/zib-BurnWound-Extent',
    'valueQuantity': {'value': 1,
     'unit': '%',
     'system': 'http://unitsofmeasure.org',
     'code': '%'}}],
  'identifier': [{'system': 'urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6',
    'value': '5460'},
   {'system': 'urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4', 'value': '3433'}],
  'clinicalStatus': 'active',
  'verificationStatus': 'unknown',
  'code': {'extension': [{'url': 'http://nictiz.nl/fhir/StructureDefinition/zib-BurnWound-BurnWoundType',
     'valueCodeableConcept': {'coding': [{'system': 'http://snomed.info/sct',
        'code': '105594005',
        'display': 'Thermische brandwond'}]}}],
   'coding': [{'system': 'http://snomed.info/sct',
     'code': '125666000',
     'display': 'Burn (disorder)'}]},
  'bodySite': [{'extension': [{'url': 'http://nictiz.nl/fhir/StructureDefinition/BodySite-Qualifier',
      'valueCodeableConcept': {'coding': [{'system': 'http://snomed.info/sct',
         'code': '24028007',
         'display': 'Right'}]}}],
    'coding': [{'system': 'http://snomed.info/sct',
      'code': '362746006',
      'display': 'structuur van oppervlak van dorsum manus'}]}],
  'subject': {'reference': 'Patient/nl-core-patient-02',
   'display': 'Jan Janssen'},
  'onsetDateTime': '2019-08-16',
  'stage': {'summary': {'coding': [{'system': 'http://snomed.info/sct',
      'code': '262588000',
      'display': '3e graad'}]}},
  'note': [{'text': 'Vuurwerk'}]}]

In [7]:
pd.json_normalize(
    fhirexample,"identifier", meta= ["id",["meta","profile"], ["subject","reference"]]
)

,system,value,id,meta.profile,subject.reference
0,urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6,1234,zib-burnwound-01,http://nictiz.nl/fhir/StructureDefinition/zib-...,Patient/nl-core-patient-01
1,urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4,4578,zib-burnwound-01,http://nictiz.nl/fhir/StructureDefinition/zib-...,Patient/nl-core-patient-01
2,urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6,5460,zib-burnwound-02,http://nictiz.nl/fhir/StructureDefinition/zib-...,Patient/nl-core-patient-02
3,urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4,3433,zib-burnwound-02,http://nictiz.nl/fhir/StructureDefinition/zib-...,Patient/nl-core-patient-02

In [8]:
pd.json_normalize(
    fhirexample,"identifier", meta= ["id",["meta","profile"], ["subject","reference"]]
)

,system,value,id,meta.profile,subject.reference
0,urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6,1234,zib-burnwound-01,http://nictiz.nl/fhir/StructureDefinition/zib-...,Patient/nl-core-patient-01
1,urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4,4578,zib-burnwound-01,http://nictiz.nl/fhir/StructureDefinition/zib-...,Patient/nl-core-patient-01
2,urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6,5460,zib-burnwound-02,http://nictiz.nl/fhir/StructureDefinition/zib-...,Patient/nl-core-patient-02
3,urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4,3433,zib-burnwound-02,http://nictiz.nl/fhir/StructureDefinition/zib-...,Patient/nl-core-patient-02

In [9]:
pd.json_normalize(
    fhirexample,record_path="identifier", meta= ["id",["meta","profile"], ["subject","reference"], ["subject","display"],["stage","summary","coding"]]
)

,system,value,id,meta.profile,subject.reference,subject.display,stage.summary.coding
0,urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6,1234,zib-burnwound-01,http://nictiz.nl/fhir/StructureDefinition/zib-...,Patient/nl-core-patient-01,Johan XXX_Helleman,"{'system': 'http://snomed.info/sct', 'code': '..."
1,urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4,4578,zib-burnwound-01,http://nictiz.nl/fhir/StructureDefinition/zib-...,Patient/nl-core-patient-01,Johan XXX_Helleman,"{'system': 'http://snomed.info/sct', 'code': '..."
2,urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6,5460,zib-burnwound-02,http://nictiz.nl/fhir/StructureDefinition/zib-...,Patient/nl-core-patient-02,Jan Janssen,"{'system': 'http://snomed.info/sct', 'code': '..."
3,urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4,3433,zib-burnwound-02,http://nictiz.nl/fhir/StructureDefinition/zib-...,Patient/nl-core-patient-02,Jan Janssen,"{'system': 'http://snomed.info/sct', 'code': '..."

In [10]:
pd.json_normalize(
    fhirexample
)

,resourceType,id,extension,identifier,clinicalStatus,verificationStatus,bodySite,onsetDateTime,note,meta.profile,code.extension,code.coding,subject.reference,subject.display,stage.summary.coding
0,Condition,zib-burnwound-01,[{'url': 'http://nictiz.nl/fhir/StructureDefin...,[{'system': 'urn:oid:2.16.840.1.113883.2.4.3.1...,active,unknown,[{'extension': [{'url': 'http://nictiz.nl/fhir...,2018-08-16,[{'text': 'Werkongeval in de hoogovens IJmuide...,[http://nictiz.nl/fhir/StructureDefinition/zib...,[{'url': 'http://nictiz.nl/fhir/StructureDefin...,"[{'system': 'http://snomed.info/sct', 'code': ...",Patient/nl-core-patient-01,Johan XXX_Helleman,"[{'system': 'http://snomed.info/sct', 'code': ..."
1,Condition,zib-burnwound-02,[{'url': 'http://nictiz.nl/fhir/StructureDefin...,[{'system': 'urn:oid:2.16.840.1.113883.2.4.3.1...,active,unknown,[{'extension': [{'url': 'http://nictiz.nl/fhir...,2019-08-16,[{'text': 'Vuurwerk'}],[http://nictiz.nl/fhir/StructureDefinition/zib...,[{'url': 'http://nictiz.nl/fhir/StructureDefin...,"[{'system': 'http://snomed.info/sct', 'code': ...",Patient/nl-core-patient-02,Jan Janssen,"[{'system': 'http://snomed.info/sct', 'code': ..."

In [11]:
pd.json_normalize(
    fhirexample, 
    record_path =['identifier'], 
    meta=['id', 'resourceType','clinicalStatus','onsetDateTime'],
    errors='ignore'
)

,system,value,id,resourceType,clinicalStatus,onsetDateTime
0,urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6,1234,zib-burnwound-01,Condition,active,2018-08-16
1,urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4,4578,zib-burnwound-01,Condition,active,2018-08-16
2,urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6,5460,zib-burnwound-02,Condition,active,2019-08-16
3,urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4,3433,zib-burnwound-02,Condition,active,2019-08-16

In [453]:
pd.json_normalize(
    fhirexample, 
    record_path =['code','extension'], 
    meta=['id', 'resourceType'],
    errors='ignore'
)

,url,valueCodeableConcept.coding,id,resourceType
0,http://nictiz.nl/fhir/StructureDefinition/zib-...,"[{'system': 'http://snomed.info/sct', 'code': ...",zib-burnwound-01,Condition
1,http://nictiz.nl/fhir/StructureDefinition/zib-...,"[{'system': 'http://snomed.info/sct', 'code': ...",zib-burnwound-02,Condition

In [13]:
pd.json_normalize(
    fhirexample, 
    record_path =['code','coding'], 
    meta=['id', 'resourceType'],
    errors='ignore'
)

,system,code,display,id,resourceType
0,http://snomed.info/sct,125666000,Burn (disorder),zib-burnwound-01,Condition
1,http://snomed.info/sct,125666000,Burn (disorder),zib-burnwound-02,Condition

In [14]:
pd.json_normalize(
    fhirexample[0]['bodySite'][0]['extension'],  
    meta=['extension', 'coding'],
    errors='ignore'
)

,url,valueCodeableConcept.coding
0,http://nictiz.nl/fhir/StructureDefinition/Body...,"[{'system': 'http://snomed.info/sct', 'code': ..."

In [15]:
fhirexample[0]['bodySite'][0]['extension']

[{'url': 'http://nictiz.nl/fhir/StructureDefinition/BodySite-Qualifier',
  'valueCodeableConcept': {'coding': [{'system': 'http://snomed.info/sct',
     'code': '24028007',
     'display': 'Right'}]}}]

In [16]:
fhirexample[0]['bodySite'][0]['extension'][0]

{'url': 'http://nictiz.nl/fhir/StructureDefinition/BodySite-Qualifier',
 'valueCodeableConcept': {'coding': [{'system': 'http://snomed.info/sct',
    'code': '24028007',
    'display': 'Right'}]}}

In [313]:
fhirexample[0]['bodySite'][0]['extension'][0].keys()

dict_keys(['url', 'valueCodeableConcept'])

In [314]:
fhirexample[0]['bodySite'][0]['extension'][0]['valueCodeableConcept']

{'coding': [{'system': 'http://snomed.info/sct',
   'code': '24028007',
   'display': 'Right'}]}

In [315]:
fhirexample[0]['bodySite'][0]['extension'][0]['valueCodeableConcept']

{'coding': [{'system': 'http://snomed.info/sct',
   'code': '24028007',
   'display': 'Right'}]}

In [316]:
fhirexample[0]['bodySite'][0]['extension'][0]['valueCodeableConcept']['coding']

[{'system': 'http://snomed.info/sct', 'code': '24028007', 'display': 'Right'}]

In [17]:
pd.json_normalize(
    fhirexample[0]['bodySite'][0]['extension'][0]['valueCodeableConcept']['coding'],  
    errors='ignore'
)

                   system      code display
0  http://snomed.info/sct  24028007   Right

In [381]:
fhirexample[0]['bodySite'][0]['extension'][0]['valueCodeableConcept']['coding']

[{'system': 'http://snomed.info/sct', 'code': '24028007', 'display': 'Right'}]

In [18]:
df_extension1 = pd.json_normalize(
    fhirexample[0], 
    record_path =['extension'], 
    meta=['id', 'resourceType'],
    errors='ignore'
)

In [21]:
df_extension2 = pd.json_normalize(
    fhirexample[1], 
    record_path =['extension'], 
    meta=['id', 'resourceType'],
    errors='ignore'
)

In [19]:
df_extension1.to_parquet('df.parquet_fhir_extension_example1.gzip',
              compression='gzip')  
pd.read_parquet('df.parquet_fhir_extension_example1.gzip')

,url,valueDateTime,valueQuantity.value,valueQuantity.unit,valueQuantity.system,valueQuantity.code,id,resourceType
0,http://nictiz.nl/fhir/StructureDefinition/cond...,2019-03-07,NaN,None,None,None,zib-burnwound-01,Condition
1,http://nictiz.nl/fhir/StructureDefinition/zib-...,None,1.0,%,http://unitsofmeasure.org,%,zib-burnwound-01,Condition

In [22]:
df_extension2.to_parquet('df.parquet_fhir_extension_example2.gzip',
              compression='gzip')  
pd.read_parquet('df.parquet_fhir_extension_example2.gzip')

,url,valueDateTime,valueQuantity.value,valueQuantity.unit,valueQuantity.system,valueQuantity.code,id,resourceType
0,http://nictiz.nl/fhir/StructureDefinition/cond...,2020-03-07,NaN,None,None,None,zib-burnwound-02,Condition
1,http://nictiz.nl/fhir/StructureDefinition/zib-...,None,1.0,%,http://unitsofmeasure.org,%,zib-burnwound-02,Condition

In [23]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("ReadingParquet").getOrCreate()
df1 = spark.read.parquet('df.parquet_fhir_extension_example1.gzip')

In [24]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("ReadingParquet").getOrCreate()
df2 = spark.read.parquet('df.parquet_fhir_extension_example2.gzip')

In [18]:
df2.show()

+--------------------+-------------+-------------------+------------------+--------------------+------------------+----------------+------------+
|                 url|valueDateTime|valueQuantity.value|valueQuantity.unit|valueQuantity.system|valueQuantity.code|              id|resourceType|
+--------------------+-------------+-------------------+------------------+--------------------+------------------+----------------+------------+
|http://nictiz.nl/...|   2020-03-07|               null|              null|                null|              null|zib-burnwound-02|   Condition|
|http://nictiz.nl/...|         null|                1.0|                 %|http://unitsofmea...|                 %|zib-burnwound-02|   Condition|
+--------------------+-------------+-------------------+------------------+--------------------+------------------+----------------+------------+

In [19]:
dfidentifier1 = pd.json_normalize(
    fhirexample[0], 
    record_path =['identifier'], 
    meta=['id', 'resourceType','clinicalStatus','onsetDateTime'],
    errors='ignore'
)

In [20]:
dfidentifier2 = pd.json_normalize(
    fhirexample[1], 
    record_path =['identifier'], 
    meta=['id', 'resourceType','clinicalStatus','onsetDateTime'],
    errors='ignore'
)

In [21]:
dfidentifier1.to_parquet('df.parquet_fhir_identifier_example1.gzip',
              compression='gzip')

In [22]:
dfidentifier2.to_parquet('df.parquet_fhir_identifier_example2.gzip',
              compression='gzip')

In [23]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("ReadingParquet").getOrCreate()
df1 = spark.read.parquet('df.parquet_fhir_identifier_example1.gzip')

In [24]:
df2 = spark.read.parquet('df.parquet_fhir_identifier_example2.gzip')

In [25]:
df1.show()

+--------------------+-----+----------------+------------+--------------+-------------+
|              system|value|              id|resourceType|clinicalStatus|onsetDateTime|
+--------------------+-----+----------------+------------+--------------+-------------+
|urn:oid:2.16.840....| 1234|zib-burnwound-01|   Condition|        active|   2018-08-16|
|urn:oid:3.16.840....| 4578|zib-burnwound-01|   Condition|        active|   2018-08-16|
+--------------------+-----+----------------+------------+--------------+-------------+

In [26]:
df2.show()

+--------------------+-----+----------------+------------+--------------+-------------+
|              system|value|              id|resourceType|clinicalStatus|onsetDateTime|
+--------------------+-----+----------------+------------+--------------+-------------+
|urn:oid:2.16.840....| 5460|zib-burnwound-02|   Condition|        active|   2019-08-16|
|urn:oid:3.16.840....| 3433|zib-burnwound-02|   Condition|        active|   2019-08-16|
+--------------------+-----+----------------+------------+--------------+-------------+

In [27]:
unionDFidentifier = df1.union(df2)
unionDFidentifier.show(truncate=False)

+------------------------------------------+-----+----------------+------------+--------------+-------------+
|system                                    |value|id              |resourceType|clinicalStatus|onsetDateTime|
+------------------------------------------+-----+----------------+------------+--------------+-------------+
|urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6|1234 |zib-burnwound-01|Condition   |active        |2018-08-16   |
|urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4|4578 |zib-burnwound-01|Condition   |active        |2018-08-16   |
|urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6|5460 |zib-burnwound-02|Condition   |active        |2019-08-16   |
|urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4|3433 |zib-burnwound-02|Condition   |active        |2019-08-16   |
+------------------------------------------+-----+----------------+------------+--------------+-------------+

In [28]:
unionDFextension = df1.union(df2)
unionDFextension.show(truncate=False)

+------------------------------------------+-----+----------------+------------+--------------+-------------+
|system                                    |value|id              |resourceType|clinicalStatus|onsetDateTime|
+------------------------------------------+-----+----------------+------------+--------------+-------------+
|urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6|1234 |zib-burnwound-01|Condition   |active        |2018-08-16   |
|urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4|4578 |zib-burnwound-01|Condition   |active        |2018-08-16   |
|urn:oid:2.16.840.1.113883.2.4.3.11.999.7.6|5460 |zib-burnwound-02|Condition   |active        |2019-08-16   |
|urn:oid:3.16.840.1.113883.2.4.3.11.999.7.4|3433 |zib-burnwound-02|Condition   |active        |2019-08-16   |
+------------------------------------------+-----+----------------+------------+--------------+-------------+

In [29]:
pandas_df_extension = unionDFextension.toPandas()

In [35]:
pandas_df_identifier = unionDFidentifier.toPandas()

In [36]:
pandas_df_identifier.to_parquet('df.parquet_fhir_identifier_total.gzip',
              compression='gzip')

In [31]:
pandas_df_extension.to_parquet('df.parquet_fhir_extension_total.gzip',
              compression='gzip')

In [32]:
parquetExtension = spark.read.parquet('df.parquet_fhir_extension_total.gzip')  
parquetExtension.createOrReplaceTempView("parquetExtension")
extension = spark.sql("SELECT * FROM parquetExtension")
extension.show()

+--------------------+-----+----------------+------------+--------------+-------------+
|              system|value|              id|resourceType|clinicalStatus|onsetDateTime|
+--------------------+-----+----------------+------------+--------------+-------------+
|urn:oid:2.16.840....| 1234|zib-burnwound-01|   Condition|        active|   2018-08-16|
|urn:oid:3.16.840....| 4578|zib-burnwound-01|   Condition|        active|   2018-08-16|
|urn:oid:2.16.840....| 5460|zib-burnwound-02|   Condition|        active|   2019-08-16|
|urn:oid:3.16.840....| 3433|zib-burnwound-02|   Condition|        active|   2019-08-16|
+--------------------+-----+----------------+------------+--------------+-------------+

In [43]:
parquetIdentifier = spark.read.parquet('df.parquet_fhir_identifier_total.gzip')  
parquetIdentifier.createOrReplaceTempView("parquetIdentfier")
identifier = spark.sql("SELECT * FROM parquetIdentfier")
identifier.show()

+--------------------+-----+----------------+------------+--------------+-------------+
|              system|value|              id|resourceType|clinicalStatus|onsetDateTime|
+--------------------+-----+----------------+------------+--------------+-------------+
|urn:oid:2.16.840....| 1234|zib-burnwound-01|   Condition|        active|   2018-08-16|
|urn:oid:3.16.840....| 4578|zib-burnwound-01|   Condition|        active|   2018-08-16|
|urn:oid:2.16.840....| 5460|zib-burnwound-02|   Condition|        active|   2019-08-16|
|urn:oid:3.16.840....| 3433|zib-burnwound-02|   Condition|        active|   2019-08-16|
+--------------------+-----+----------------+------------+--------------+-------------+

In [57]:
query = spark.sql("SELECT e.value AS value_extension, i.* FROM parquetIdentfier i INNER JOIN parquetExtension e ON i.id = e.id AND e.value = 1234")
query.show()

+---------------+--------------------+-----+----------------+------------+--------------+-------------+
|value_extension|              system|value|              id|resourceType|clinicalStatus|onsetDateTime|
+---------------+--------------------+-----+----------------+------------+--------------+-------------+
|           1234|urn:oid:2.16.840....| 1234|zib-burnwound-01|   Condition|        active|   2018-08-16|
|           1234|urn:oid:3.16.840....| 4578|zib-burnwound-01|   Condition|        active|   2018-08-16|
+---------------+--------------------+-----+----------------+------------+--------------+-------------+